[project]
name = "mytimes"
version = "0.1.0"
description = "A personal time tracking application made with Streamlit ðŸŽˆ."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.17.0",
    "streamlit>=1.51.0",
]
